export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_FAIL = "UPLOAD_FILE_FAIL"
export const UPLOAD_FILE_RESET = "UPLOAD_FILE_RESET"

export const GET_FILE_REQUEST = "GET_FILE_REQUEST"
export const GET_FILE_SUCCESS = "GET_FILE_SUCCESS"
export const GET_FILE_FAIL = "GET_FILE_FAIL"
export const GET_FILE_RESET = "GET_FILE_RESET"

export const GET_FILES_REQUEST = "GET_FILES_REQUEST"
export const GET_FILES_SUCCESS = "GET_FILES_SUCCESS"
export const GET_FILES_FAIL = "GET_FILES_FAIL"
export const GET_FILES_RESET = "GET_FILES_RESET"