export const SIGNIN_USER_REQUEST="SIGNIN_USER_REQUEST"
export const SIGNIN_USER_SUCCESS="SIGNIN_USER_SUCCESS"
export const SIGNIN_USER_FAIL="SIGNIN_USER_FAIL"
export const SIGNIN_USER_RESET="SIGNIN_USER_RESET"

export const SIGNOUT_USER="SIGNOUT_USER"

export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL"
export const REGISTER_USER_RESET="REGISTER_USER_RESET"

export const LIST_USERS_REQUEST="LIST_USERS_REQUEST"
export const LIST_USERS_SUCCESS="LIST_USERS_SUCCESS"
export const LIST_USERS_FAIL="LIST_USERS_FAIL"

export const UPDATE_USER_ROLE_REQUEST="UPDATE_USER_ROLE_REQUEST"
export const UPDATE_USER_ROLE_SUCCESS="UPDATE_USER_ROLE_SUCCESS"
export const UPDATE_USER_ROLE_FAIL="UPDATE_USER_ROLE_FAIL"
export const UPDATE_USER_ROLE_RESET="UPDATE_USER_ROLE_RESET"